blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/lsdcapital/git-branch-keeper/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/lsdcapital/git-branch-keeper#readme
    about: Read the documentation for usage help
